"use strict";
exports.__esModule = true;
var x = true;
console.log(x);
console.log();
var y = 1;
console.log(y);
console.log();
var name = "Maharshi";
console.log(name);
console.log();
var a = null;
var b = undefined;
console.log(a, b);
console.log();
var list1 = [1, 2, 3];
console.log(list1);
console.log();
var list2 = [1, 2, 3];
console.log(list2);
console.log();
var person = ["Maharshi", 20];
console.log(person);
var colors;
(function (colors) {
    colors[colors["red"] = 0] = "red";
    colors[colors["blue"] = 1] = "blue";
    colors[colors["green"] = 2] = "green";
})(colors || (colors = {}));
var c = colors.blue;
console.log(c);
console.log();
var random = 20;
console.log(random);
random = "Maharshi";
console.log(random);
random = true;
console.log(random);
console.log(random.name);
console.log();
var random1 = 20;
console.log(random1);
random1 = "Maharshi";
console.log(random1);
random1 = true;
console.log(random1);
console.log();
var multi;
multi = "Maharshi";
console.log(multi);
multi = 10;
console.log(multi);
